### ISSUE TITLE
Pull request for the issues

### ISSUE THREAD

**Issue by altuga** [leasingninja/leasingninja-java-boundedcontexts-domainmodel#2]
Hello Henning

Are there any target conditions for https://leasingninja.io/  java based app ? 
Below issues should be merged to the main branch.  I already send a pull request for the below issues. If are there any obstacle that I don't know please inform me. 

1- application.properties - added
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=create

2 - sales/module-info.java

requires org.jmolecules.ddd;

3- contract.html

Thanks

**Comment by hschwentner** [comment]
Hi Altuğ,

thanks again for your support! The main obstacle is that I just couldn’t finde the time yet; sorry! I started to review the PR and it is in a way two PRs in one. :-) The application.properties part is easy to review but I need a bit of time to look into the credit rating part. Hm, maybe I can cherry pick the application property part.

Best,
Henning

**Comment by hschwentner** [comment]
Merged the PR. Will have to work on the credit rating to make explicit what I mean with that :-)
