### ISSUE TITLE
InaccessibleObject

### ISSUE THREAD

**Issue by altuga** [leasingninja/leasingninja-java-boundedcontexts-domainmodel#3]
I'm using JDK 17 and IntelliJ IDEA 2021.3 (Ultimate Edition)

I can build the project via **mvn clean compile** but I couldn't run the test when I type **mvn clean install** 
Error message : 

[ERROR] Errors: 
[ERROR]   CheckCreditRatingTest.givenAContract_whenCheckCreditRating_thenContractRated » InaccessibleObject
[ERROR]   CheckCreditRatingTest.testDomainLayerIntegrationTest » InaccessibleObject Unab...
[ERROR]   InboxApplicationServiceTest.givenAnEmptyInbox_whenConfirmSignedContract_thenContractIsSaved » InaccessibleObject
[ERROR]   ListContractsTest.givenAContract_whenRead_thenContractIsRead » InaccessibleObject
[ERROR]   ReadContractTest.givenAContract_whenRead_thenContractIsRead » InaccessibleObject
[ERROR]   VoteContractTest.givenARatedContract_whenVote_thenContractVoted » InaccessibleObject
[ERROR]   ContractTest.givenARatedContract_whenVote_ThenVoted » InaccessibleObject Unabl...
[ERROR]   ContractTest.givenASignedContract_whenCheckCreditRating_ThenRated » InaccessibleObject
[ERROR]   ContractTest.restoreContract » InaccessibleObject Unable to make io.leasingnin...
[ERROR]   ContractModelMapperTest.givenARatedButUnvotedContract_whenMapped_thenUnvotedModel » InaccessibleObject
[ERROR]   ContractModelMapperTest.givenAVotedContract_whenMapped_thenUnvotedModel » InaccessibleObject
[ERROR]   ContractModelMapperTest.givenAnUnratedContract_whenMapped_thenUnvotedModel » InaccessibleObject
[INFO] 
[ERROR] Tests run: 12, Failures: 0, Errors: 12, Skipped: 0

I guess something is missing in the **module-info.java**, any idea? 

Thanks.

**Comment by hschwentner** [comment]
Yes, somehow the tests cannot access into a Jigsaw module. Ugly workarounds:

1. remove module-info.java for testing
2. `mvn install` with `-Dmaven.test.skip=true`

**Comment by altuga** [comment]
Remove module-info.java for testing works.
Also I had problem to run the spring app, after removing module-info.java  all works. 

Are there any reason to use module-info.java in that project? 

Thanks.
